### ISSUE TITLE
Point().selected ?

### ISSUE THREAD

**Issue by BlackFoundry** [fonttools/ufoLib2#14]
What do you think of having a .selected (bool) property for the Point class ?

**Comment by madig** [comment]
I am not sure this can be meaningfully integrated into ufoLib2, as it is essentially a "headless" library to access UFO data. A `.selected` property implies that there is a GUI present somewhere. What are trying to achieve? Maybe https://github.com/robotools/fontParts suits your needs better?

**Comment by BlackFoundry** [comment]
yeah but fontParts too much wrapper and slow, and Point() don't have a selection flag either.
I tried it first :) it's nice an easy to use but too slow.
I tried adding my own .selected @property to the ufoLib2 Point() class but don't want to subclass everything above (contour, paths, glyph…)
Experimenting with GUI indeed  :)

**Comment by BlackFoundry** [comment]
Thinking of it, guidelines are also implying a GUI somehow and don't exist in binary fonts; I mean they are only meaningful if there is a GUI so, why not a .selected for Points, and maybe even for other objects.

**Comment by madig** [comment]
The thing about guidelines is that they are [actual pieces of data stored in UFOs](http://unifiedfontobject.org/versions/ufo3/glyphs/glif/#guideline). There is no data structure to represent a selected point.

Are you experimenting with Trufont-WX? You might be able to make a new class `UIPoint` or somesuch where you add the `selected` data and property and then use it, but I'm not yet familiar enough with the guts of Trufont.

**Comment by BlackFoundry** [comment]
yeah exactly
What troubles me is that I would basically have to make a whole UI_UFO… that would have a Writer to actually apply changes to the real UFO… I was dreaming of something more direct and lightweight.

**Comment by madig** [comment]
I currently can't help you with that 😞 You might want to contact Adrien if he has an idea.

I will close this issue for now. If it turns out that something can be done on the ufoLib2 side, this can be reopened.

**Comment by BlackFoundry** [comment]
Sorry to re-open this but I think it is going beyond TruFont specific stuff.
What I mean is that we have UI inherited stuff in the UFO format (like .smooth that come from Fontographer's UI –and that is very handy to have indeed in the format) so why not having a .selected in the UFO format too ? @typesupply

**Comment by typesupply** [comment]
Could you open an issue about this on the UFO spec repository? I'd prefer that the discussion about UFO changes be there. Thanks!

**Comment by BlackFoundry** [comment]
done :)
