### ISSUE TITLE
Should not require wheel to run setuptools locally

### ISSUE THREAD

**Issue by alerque** [fonttools/ufoLib2#156]
Carbon copy of https://github.com/googlefonts/glyphsLib/issues/701 ...

---

Having inherited packaging duties for a dozen or so Python font related libraries on Arch Linux I'm working my way through cleaning them up. Something is amiss with this one:

https://github.com/fonttools/ufoLib2/blob/b4c0ee7858e715390118f1942177a218d68a5810/setup.cfg#L26

Similar to [this PR on booleanOperations](https://github.com/typemytype/booleanOperations/pull/63) I think deleting this entirely is correct (using setuptools locally shouldn't require it), but unlike on that PR I'm not so confident the rest of the project (CI tooling, other Python build tooling, etc.) is setup to handle it properly if just deleted outright without making other adjustments first so the `bdist` builds keep working.

I'm happy to submit a PR to drop this but first somebody more familiar with the release process should confirm.

**Comment by madig** [comment]
I'm not familiar with the best practice regarding this, but I do remember that there were problems at some point with wheel not being available and CI failing because no wheels could be made.

**Comment by anthrotype** [comment]
it's fine to remove it from setup_requires, we install it manually just before calling bdist_wheel

https://github.com/fonttools/ufoLib2/blob/b4c0ee7858e715390118f1942177a218d68a5810/.github/workflows/publish.yml#L24

But we do want to keep `wheel` listed in pyproject.toml as is recommended by PyPA packaging guide
