### ISSUE TITLE
Font() no longer takes parameters, breaking docs (and backwards compatibility)

### ISSUE THREAD

**Issue by simoncozens** [fonttools/ufoLib2#184]
This used to work:

```python
>>> from ufoLib2.objects import Font
>>> Font("foo.path")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() takes 1 positional argument but 2 were given
```

and the docs suggest it should:

https://github.com/fonttools/ufoLib2/blob/512f5e96700e65f1eca860dcc396606a9829fdfc/src/ufoLib2/objects/font.py#L48-L72

This means any code which previously did this:

```
ds = DesignSpaceDocument.fromfile(designspace_path)
ds.loadSourceFonts(ufoLib2.objects.Font)
```

probably needs to change to

```
ds = DesignSpaceDocument.fromfile(designspace_path)
ds.loadSourceFonts(ufoLib2.objects.Font.open)
```

which is fine, but breaks the parallel with Defcon.

**Comment by anthrotype** [comment]
yes, I am sorry about that. We did it intentionally (#176), but I forgot to also update the docs. With hindsight we should have at least provided a deprececationwarning cycle. It shall not happen again, promise.

**Comment by rimas-kudelis** [comment]
@anthrotype, you closed this as completed, but still failed to update the docs. It's been almost three years now.

**Comment by anthrotype** [comment]
well, I did update the docs with https://github.com/fonttools/ufoLib2/commit/fcdce791a23296fe045a8f07d9a8c8b17c8bc50c (linked in my previous comment) hence why this issue got closed. 
But I can see that https://ufolib2.readthedocs.io/en/latest/reference.html#font didn't get updated. It wasn't me who set up the Read The Docs integration, i'm not sure what's going on to be honest.
Maybe @madig can help?

**Comment by madig** [comment]
I updated the ReadTheDocs configuration and the new docs are live at https://ufolib2.readthedocs.io/en/latest/reference.html#font,

**Comment by rimas-kudelis** [comment]
@madig, what about docs for `stable`? I suspect they too should be updated, no?

**Comment by madig** [comment]
Yes, but I think I have to make a release for this, which I'm currently too lazy to do. Maybe later.
