### ISSUE TITLE
ufoLib2.Font.open() fails if woff attributes present in fontinfo.plist

### ISSUE THREAD

**Issue by DavidRaymond** [fonttools/ufoLib2#205]
We discovered this using glyphsLib's ufo2glyphs with a ufo that had had woffMetadataCredits and woffMetadataDescription in fontinfo.plist but I've since reproduced this just with ufoLib2 code.

To reproduce the error:

- Clone Nokyung font from commit https://github.com/silnrsi/font-nokyung  (I was using the latest commit, 3e384ad)
- Run the following python code in the top level of the Nokyung repository:

```
#!/usr/bin/env python
import ufoLib2
font = ufoLib2.Font.open("source/Nokyung-Regular.ufo")
```

It will fail with a traceback saying:

`fontTools.ufoLib.errors.UFOLibError: The supplied info object does not support setting a necessary attribute (woffMetadataCredits)`

**Comment by DavidRaymond** [comment]
The ufo will open in the following woff attributes are added to  ufoLib2/src/ufoLib2/objects/info.py as follows
```postscriptDefaultCharacter: Optional[str] = None
    postscriptWindowsCharacterSet: Optional[str] = None

    woffMetadataCredits: Optional[List[str]] = None
    woffMetadataDescription: Optional[List[str]] = None

    # old stuff
    macintoshFONDName: Optional[str] = None
```

**Comment by anthrotype** [comment]
actually it works for me using the latest ufoLib2 0.13.1 (I just tried).
Note that we added support for woff metadata in fontinfo.plist only recently, in 0.13.0 I think
