### ISSUE TITLE
Tests need to adapt to cattrs >= 22.1 new validation mode

### ISSUE THREAD

**Issue by madig** [fonttools/ufoLib2#224]
See https://github.com/python-attrs/cattrs/blob/main/HISTORY.rst#2210-2022-04-03.

Running the tests with the latest cattrs errors out because some exception regexes now would need to dig into the returned error object or something. Disabling extra validation should make it work but eh?

**Comment by anthrotype** [comment]
is it only the tests that fail, or is ufoLib2 lib incompatible with cattrs >= 22.1?

**Comment by madig** [comment]
The tests fail because the new validation returns different exceptions (or wrappers, IIUC), happy path functionality is unchanged.

**Comment by anthrotype** [comment]
Fixed with #230
