### ISSUE TITLE
`Glyph.name` being Noneable is annoying

### ISSUE THREAD

**Issue by madig** [fonttools/ufoLib2#231]
I know it's for defcon compatibility, but the type checkers keep nagging me whenever I do anything with the name.

**Comment by anthrotype** [comment]
What do you suggest? make it required str? that would be a breaking change indeed. It's also a redundant piece of info most of the time, it's already embedded in the key of the layer dictionary (or the contents.plist), and potentially ought to be removed altogether from the GLIF structure in some future versions of UFO

**Comment by anthrotype** [comment]
basically a Glyph in which the name is None is a layer-less glyph floating in vacuum, whereas ufoLib2 Layer guarantees that all its Glyph objects have a (read-only) name attribute that matches the key that are assigned to in the layer internal dict.
If your typechecker dislikes the optionality of the Glyph.name, either you assert it's not None before using it (when you know it comes from a layer) or simply not use it and use the key

**Comment by anthrotype** [comment]
> if Font/Layer had an .items() work-alike :)

that we can surely add without breaking backward compat

**Comment by anthrotype** [comment]
was it not required at some point in the past and then we changed it to optional? I don't recall the exact history

**Comment by madig** [comment]
Yes, for defcon compat I think.
