### ISSUE TITLE
Should objects be compared using value or identity? 

### ISSUE THREAD

**Issue by madig** [fonttools/ufoLib2#24]
Currently, ufoLib2 objects have `cmp=True` set, making equality-testing use their values and making them not hashable. Defcon objects are compared using their identity instead, making them hashable. Should ufoLib2 do the same?

**Comment by anthrotype** [comment]
if they were frozen they could be _both_ hashable and comparable by value... (just sayin')

**Comment by anthrotype** [comment]
we compare by value
