### ISSUE TITLE
msgpack also required for json output

### ISSUE THREAD

**Issue by madig** [fonttools/ufoLib2#245]
This code triggers a msgpack import (neither json nor msgpack extra is installed):

```py
ufo = Font.open("some.ufo")
ufo.json_dump("a.json")
```

Can't even seem to catch it using `except Exception as e` in `def serde`. A missing cattrs import ends the script as well.

**Comment by anthrotype** [comment]
ok, so this issue triggers only if one `pip install ufoLib2` version 0.14.0 without any extras and then one tries to call the `{json,msgpack}_dump{,s}` methods.
If I one does `pip install ufoLib2[json]` the `json_dump/json_dumps` methods work, similarly for `ufoLib2[msgpack]` and `msgpack_dump/msgpack_dumps`.

#246 should improve the UX and give a more meaningful error message when one tries to call any of these optional features without having the respective extras installed.
