### ISSUE TITLE
Use pathlib.Path for path objects

### ISSUE THREAD

**Issue by madig** [fonttools/ufoLib2#26]
Eliminate `os.path` usage.

**Comment by anthrotype** [comment]
I take that you like pathlib, but I don't think using os.path is a sin

**Comment by anthrotype** [comment]
the Font.path (traditionally, as in defcon, robofab, fontParts, etc.) has been a simple string. I would not change that for backward compatibility reasons. We could add an additional property to return the pathlib.Path but user can do that if they wish.
If you mean, replacing the use of os.path internally (e.g. in Font.save() method), sure, go on with it. It won't change a thing.

**Comment by madig** [comment]
I'd use it internally.

Maybe for a refactoring at some point.
