### ISSUE TITLE
Latest release (0.15.0) is not on PyPI

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/ufoLib2#281]
The latest release available through [PyPI is 0.14.0](https://pypi.org/project/ufoLib2/). Is there any reason for this?

**Comment by anthrotype** [comment]
yes, we had to "yank" it because we too hurriedly released it with a change that we later on decided to revert, see https://github.com/fonttools/ufoLib2/pull/276

**Comment by jenskutilek** [comment]
Ah, I missed that. Thanks.
