### ISSUE TITLE
Font.glyphOrder always constructs new list

### ISSUE THREAD

**Issue by madig** [fonttools/ufoLib2#30]
```
>>> u = ufoLib2.Font()
# ...

>>> u.glyphOrder
[]

>>> u.glyphOrder.append("a")

>>> u.glyphOrder
[]
```
Not sure if this should be changed or stay as is...

**Comment by madig** [comment]
Heh. It's not even possible to do 
```
u = ufoLib2.Font()
u.glyphOrder = []
u.glyphOrder.append("a")
```
because the setter checks for `len == 0` values and deletes the key then instead.

**Comment by madig** [comment]
Maybe it should return a `tuple`.

**Comment by anthrotype** [comment]
this is a defcon-ism
https://github.com/robotools/defcon/blob/2c530ff14912603fc1bf0e87749423f8a9a5fe39/Lib/defcon/objects/font.py#L627

let's document that it always returns a copy and move on

**Comment by madig** [comment]
Done already.
