### ISSUE TITLE
Allow glyph copying by assignment

### ISSUE THREAD

**Issue by madig** [fonttools/ufoLib2#33]
This code snippet should copy the entire glyph including outlines and components from one Font object to another: `newfont["some_glyph"] = oldfont["some_glyph"]` without me having to reach for pens.

**Comment by anthrotype** [comment]
shouldn't `newfont["some_glyph"] = copy.deepcopy(oldfont["some_glyph"])` already work?

**Comment by madig** [comment]
I found that this actually works.
