### ISSUE TITLE
Write fontinfo.plist when all attributes are None?

### ISSUE THREAD

**Issue by madig** [fonttools/ufoLib2#38]
I found that ufonormalizer deletes fontinfo.plist from a UFO when it's empty. I wonder if ufoLib2  should do the same, instead of writing out `<dict/>`.

**Comment by anthrotype** [comment]
yes, it's optional, we should not write if empty

**Comment by madig** [comment]
Hm, should this be done in ufoLib2 or in ufoLib? The latter fetches all attributes from the object already and always writes a file, even with no attributes.

**Comment by anthrotype** [comment]
then it should be ufoLib

**Comment by madig** [comment]
Fixed in https://github.com/fonttools/fonttools/pull/1911.
