### ISSUE TITLE
Introduce strict type checking

### ISSUE THREAD

**Issue by madig** [fonttools/ufoLib2#42]
Mypy needs annotations for function parameters _and_ their return value, otherwise, checking is silently very limited.

1. Annotate everything
2. Toggle flags described in https://mypy.readthedocs.io/en/latest/config_file.html#untyped-definitions-and-calls (plus other strictness flags described on that page) for maximum strictness.
3. Make mypy give the code a pass.

It may be nice to be able to use https://mypy.readthedocs.io/en/latest/protocols.html#simple-user-defined-protocols, but it requires an additional dependency for Python < 3.8.

It would also be nice to be able to use Python 3.7's [`from __future__ import annotations`](https://www.python.org/dev/peps/pep-0563/) to make some annotations less fiddly and not incur an import loading time penality but oh well.

**Comment by madig** [comment]
Also: how to provide typing information for mypy so ufoLib2 can easily be mypy'd as an external library? 

Related: https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports

**Comment by anthrotype** [comment]
is this completed yet, @madig? 

don't we need to add a `py.typed` thingy as of https://www.python.org/dev/peps/pep-0561/

**Comment by madig** [comment]
Not yet, we have to annotate _everything_ first so we can make mypy be a strict as possible. I tried this last time and got stuck at all the generic dunder methods and how to annotate them in a way mypy is happy with,

**Comment by anthrotype** [comment]
> generic dunder methods

Which ones?

**Comment by madig** [comment]
All the `__getitem__` etc ones inherited from MutableMapping and others.
