### ISSUE TITLE
Should adding/removing glyphs update ufo.glyphOrder?

### ISSUE THREAD

**Issue by madig** [fonttools/ufoLib2#50]
Defcon creates/appends to a `ufo.lib["public.glyphOrder"]` list on adding new glyphs. The parameter is optional, but it does make sense to mirror defcon here because AFAIK that key is the only place that stores the actual order of glyphs. One could reasonably expect that if you add `c`, `a`, `f` in that order that it stays in that order on load.

**Comment by anthrotype** [comment]
For simplicity I think it's preferable to keep as it is. The `glyphOrder` property simply reads/writes from the public.glyphOrder key and leaves it to the client/user to maintain that list, if they wish to do so. It is optional, and authoring tools are not even required to use it, says UFO spec.
