### ISSUE TITLE
Implement glyph sidebearings getter and setter

### ISSUE THREAD

**Issue by madig** [fonttools/ufoLib2#52]
Needs an optional `glyph_set` parameter to look up components.

Related: https://github.com/fonttools/ufoLib2/issues/22

**Comment by anthrotype** [comment]
We need to add these methods to the Glyph class

```
def getLeftMargin(self, layer=None)

def setLeftMargin(self, value, layer=None)

def getRightMargin(self, layer=None)

def setRightMargin(self, value, layer=None)
```

for #22 we need related methods:

```
def getBounds(self, layer=None)

def getControlBounds(self, layer=None)
```

**Comment by anthrotype** [comment]
we would never be able to replicate defcon's `leftMargin` etc. property getters/setters because our Glyph object by design does not hold a back-reference to its parent Layer, and we would like to keep it that way.
