### ISSUE TITLE
Idea, typing: GlyphSet protocol

### ISSUE THREAD

**Issue by madig** [fonttools/ufoLib2#58]
Since all UFO layers are self-contained, sometimes you don't care if you pass a Font or a Layer into a function. Making a GlyphSet protocol could open this to type checking.

**Comment by anthrotype** [comment]
sure. but isn't Protocol only available as of python 3.8?
https://docs.python.org/3/library/typing.html#typing.Protocol

**Comment by madig** [comment]
Yeah, but there's typing_extensions or something before < 3.8.

**Comment by anthrotype** [comment]
nice! ok

**Comment by madig** [comment]
Roadblock: the following code in typing.py would be what I want:

```python
class GlyphSet(Protocol):
    def __getitem__(self, name: str) -> Glyph:
        ...
```

Unfortunately, it would require importing Glyph, creating a circular import. One can do

```python
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ufoLib2.objects.glyph import Glyph
```

But this makes mypy blow up in other modules, presumably due to the circular import. The code probably needs to be restructured to avoid this.

**Comment by anthrotype** [comment]
Why do you need a GlyphSet protocol? Can't you simply alias GlyphSet = Mapping[str, Glyph] ?

**Comment by madig** [comment]
That would work but still require a circular import :(

**Comment by madig** [comment]
Implemented with https://github.com/fonttools/ufoLib2/pull/123.
