### ISSUE TITLE
Library name question

### ISSUE THREAD

**Issue by benkiel** [fonttools/ufoLib2#71]
All, I know this is still a work in progress, but I figured raising this now makes sense: my understanding from the code is that this isn't replacing `fonttools.ufolib` as I don't see the reader/writer. I am 100% good with that, as so many things rely on `fonttools.ufolib`. However, that makes the name for this package confusing, as it is more of an alternate defcon, not a ufolib replacement. I don't have a good name suggestion, but I do think this is confusing and it should have another name.

**Comment by anthrotype** [comment]
Yeah the name isn't great, but originally the idea was to fold it into fontTools.ufoLib. I would like to finish that someday.

**Comment by madig** [comment]
Fold it into `fontTools.ufoLib.objects` to be specific :)
