### ISSUE TITLE
Try very hard not to use Glyph.name anywhere

### ISSUE THREAD

**Issue by madig** [fonttools/ufoLib2#75]
so we can kill it for the hypothetical next UFO version

**Comment by anthrotype** [comment]
the same issue arguably applies for Layer.name.
I am not sure how this can be solved in a compatible way.

**Comment by anthrotype** [comment]
FWIW we already do not rely on Glyph.name internally in ufoLib2. We only use it in layer module where we need to adjust the glyph names of newly added glyphs.

**Comment by madig** [comment]
`name` is a read-only property in both Layer and Glyph, maybe we're good already? The name should always be taken from LayerSet and Layer, respectively.

**Comment by madig** [comment]
It can be copied from the parent container so we can reference it, even if it's not present in the serialized format.

**Comment by anthrotype** [comment]
Yes, i think we're good. If and when UFO spec gets rid of it we can revise.
