### ISSUE TITLE
Layers not automatically loaded on iteration?

### ISSUE THREAD

**Issue by madig** [fonttools/ufoLib2#8]
I'm trying to add conversion of all layers to tfont's `UFOConverter` and ran into the following problem when trying to convert Ubuntu-R.ufo:
```
In [1]: import ufoLib2

In [2]: u=ufoLib2.Font.open("Ubuntu/source/Ubuntu-R.ufo/")

In [3]: for l in u.layers:
   ...:     print(repr(l))
   ...: 
<ufoLib2.objects.layer.Layer 'public.default' (1264 glyphs) at 0x7f51e06e57d8>
<object object at 0x7f51e1915ab0>

In [4]: u.layers["public.background"]                                           
Out[4]: <ufoLib2.objects.layer.Layer 'public.background' (508 glyphs) at 0x7f51e06feba0>
```
The background layer isn't loaded automatically when iterating over it? This breaks iterating over layers in search of tfont glyph layers to add.

**Comment by anthrotype** [comment]
It’s loaded lazily as you getitem.
Iter method used in the for loop should be changed so that it triggers the lazy-loading
